_target_: models.modules.trm_diffusion.LanguageTRMModule
sample_scheduler:
  _target_: utils.sample_schedulers.LinearEntropyBatchSampleScheduler
  steps_per_batch: 10
  batch_length: 16
  # _target_: utils.sample_schedulers.LinearSampleScheduler
  # num_steps: 32
model: ${model}
latent_len: 1024
supervision_steps: 16
learning_params: ${learning}
loss_aggregator: ${loss.aggregator}
optimizer_cfg: ${optimizer}
scheduler_cfg: ${scheduler}
