defaults:
  - _self_
  - data: dllm
  - learning: standard
  - optimizer: adamw_standard
  - scheduler: one_cycle_lr
  - loss: lctm
  - model: lctm
  - module: autoregressor

project_name: LightningTemplate
model_name: lctm
resume: null

# Optimizations
use_torch_compile: False
seq_length: 1024
